services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: llmgateway
      POSTGRES_PASSWORD: llmgateway
      POSTGRES_DB: llmgateway
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"   # Tempo HTTP API (Grafana lo usa)
      - "4318:4318"   # OTLP HTTP receiver
      - "4317:4317"   # OTLP gRPC receiver (por si acaso)

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./docker/loki/loki.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

#  llmgateway:
#    build: .
#    depends_on:
#      - postgres
#    environment:
#      GATEWAY_PROVIDERS_OLLAMA_BASE_URL: http://host.docker.internal:11434
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/llmgateway
#      SPRING_DATASOURCE_USERNAME: llmgateway
#      SPRING_DATASOURCE_PASSWORD: llmgateway
#      # más env vars cuando integremos postgres en Fase 4
#    ports:
#      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
  tempo-data:
  loki-data:
  grafana-data: