spring:
  application:
    name: llmgateway
  datasource:
    url: jdbc:postgresql://localhost:5432/llmgateway
    username: llmgateway
    password: llmgateway
  flyway:
    enabled: true
    locations: classpath:db/migration
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        enabled: false # importante: no quieres el chat de Spring AI
      embedding:
        enabled: true
        options:
          model: nomic-embed-text

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        llmgateway.provider.latency: true
        llmgateway.embedding.latency: true
  tracing:
    enabled: true
    sampling:
        probability: 1.0
    baggage:
      correlation:
        enabled: true
        fields:
          - traceId
          - spanId
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: http://localhost:3100/otlp/v1/logs
    instrumentation:
      logback-appender:
        capture-experimental-attributes: true
        capture-key-value-pair-attributes: true

logging:
  pattern:
    level: "%5p [%X{requestId:-}] [%X{tenantId:-}] [%X{traceId:-},%X{spanId:-}]"

gateway:
  cache:
    similarity-threshold: 0.15
  rate-limit:
    enabled: true
    capacity: 10
    refill-tokens: 10
    refill-period-seconds: 60
  security:
    api-keys:
      - key: sk-test-alice
        tenant-id: alice-corp
      - key: sk-test-bob
        tenant-id: bob-startup
  providers:
    ollama:
      base-url: http://localhost:11434
    mock:
      enabled: true
      supported-models: mock-fast,mock-slow
      fail-rate: 0.0
      latency-ms: 0
